spring.profiles.include: 'service-config'
spring:
  profiles:
    active: local_h2
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:    pathmatch:      matching-strategy: ANT_PATH_MATCHER
server:
  port: 7001
  servlet:
    contextPath:
security:
  sessions: STATELESS
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmLaMuIVz46ok3XByOYLY
          UYttDXMmi/74taY/XQfL+vlb4P3aGCoCbDJFNeM4XBNZXcSBfsaH1xsa+M9Hx05U
          NeNj11cv7wK8BKVNA+l9DyIjjW0IcXlKjtzv/qXZjPE98igWvyc84LzkILQYwIwX
          G6gAdS6CMnzvYomrt0VjyRquUT2mawJfs60HQkwsj4t0JrWjVufVA1BErLpgdhR8
          IlM5n9IrgjN8JAt8PpdBttOKDGq/g/UzzLNYi0TyLYooOd/MZeXyjdN7tj5Vwt3m
          vG70+b99Q6FxGFIFQ5NKavr8/eLBO69E9P6Qzzg0mD/nOP82NRtDVmb5B1j0idJb
          AwIDAQAB
          -----END PUBLIC KEY-----
---
spring:
  profiles: unittest
security:
  basic:
    enabled: false
---
spring:
  profiles: local
#security:
#  user:
#    name: admin
#    password: admin
#    role: ALL
---
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:        trace: true
        web-allow-others: false
  profiles: local_h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  sql:    init:      platform: h2
      
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
    defer-datasource-initialization: true
  jta:
    enabled: false
debug: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
