-- USER -
INSERT INTO USERS (USER_ID, USER_NAME, PASS_WORD, FIRST_NAME, LAST_NAME) VALUES (1, 'username01', '123456', 'Nguyen', 'A');
INSERT INTO USERS (USER_ID, USER_NAME, PASS_WORD, FIRST_NAME, LAST_NAME) VALUES (2, 'username02', '123456', 'Pham', 'B');
INSERT INTO USERS (USER_ID, USER_NAME, PASS_WORD, FIRST_NAME, LAST_NAME) VALUES (3, 'username03', '123456', 'Ly', 'C');

-- USER_ROLES -
INSERT INTO USER_ROLES (USER_ROLE_ID, IS_ACTIVE, ROLE_NAME) VALUES (1, 1, 'Administrator');
INSERT INTO USER_ROLES (USER_ROLE_ID, IS_ACTIVE, ROLE_NAME) VALUES (2, 1, 'User');
INSERT INTO USER_ROLES (USER_ROLE_ID, IS_ACTIVE, ROLE_NAME) VALUES (3, 1, 'Guest');
